name: Auto label Pull Requests

# **What it does**: Automatically adds the engineering label when specific files change.
# **Why we have it**: Other automation applies specifically to engineering label issues and pull requests.
# **Who does it impact**: Automation that relies on the engineering label.

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
      # See labeling configuration in the `.github/labeler.yml` file
      - uses: actions/labeler@9fcb2c2f5584144ca754f8bfe8c6f81e77753375
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
